export interface IProduct {
  _id: string;
  name: string;
  sku: string;
  slug: string;
  newCategoryId: string;
  image?: string;
  image1?: string;
  image2?: string;
  video?: string;
  structureId: string;
  contentId: string;
  gsm: number;
  oz: number;
  cm: number;
  inch: number;
  quantity: number;
  um: string;
  currency: string;
  finishId: string;
  designId: string;
  colorId: string;
  css: string;
  motifsizeId: string;
  suitableforId: string;
  vendorId: string;
  groupcodeId: string;
  charset?: string;
  xUaCompatible?: string;
  viewport?: string;
  title?: string;
  description?: string;
  keywords?: string;
  robots?: string;
  contentLanguage?: string;
  googleSiteVerification?: string;
  msValidate?: string;
  themeColor?: string;
  mobileWebAppCapable?: boolean;
  appleStatusBarStyle?: string;
  formatDetection?: string;
  ogLocale?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogType?: string;
  ogUrl?: string;
  ogSiteName?: string;
  twitterCard?: string;
  twitterSite?: string;
  twitterTitle?: string;
  twitterDescription?: string;
  hreflang?: string;
  x_default?: string;
  author_name?: string;
  excerpt?: string;
  canonical_url?: string;
  description_html?: string;
  rating_value?: number;
  rating_count?: number;
  purchasePrice: number;
  salesPrice: number;
  locationCode: string;
  productIdentifier: string;
  published_at?: string;
  updated_at?: string;
}

export interface IProductFormData {
  name: string;
  sku: string;
  slug: string;
  newCategoryId: string;
  gsm: number;
  oz: number;
  cm: number;
  inch: number;
  quantity: number;
  um: string;
  currency: string;
  structureId: string;
  contentId: string;
  finishId: string;
  designId: string;
  colorId: string;
  css: string;
  motifsizeId: string;
  suitableforId: string;
  vendorId: string;
  groupcodeId: string;
  purchasePrice: number;
  salesPrice: number;
  locationCode: string;
  productIdentifier: string;
  image?: File | null;
  image1?: File | null;
  image2?: File | null;
  video?: File | null;
}

export interface IFilter {
  name: keyof IProductFormData;
  label: string;
  options: Array<{ _id: string; name: string }>;
}
